uxsolutions/bootstrap-datepicker

- docs/options.rst
Added docs for the new option introduced in #515
> Added docs for datesDisabled #515

- docs/options.rst
- js/bootstrap-datepicker.js
- tests/suites/options.js
new feature : container option
Basically adds a container option, which takes a string "css selector" as per boot strap tooltips http://getbootstrap.com/javascript/#tooltips 
(useful for me, as I'm playing with zoom and transforms in my project and want the date picker popup to have these applied without hacks)
https://github.com/eternicode/bootstrap-datepicker/issues/896
ps first time pull requesting, apologies if i'm doing something wrong
> adding container option, and tests

- docs/REAME.md
- docs/conf.py
- docs/requirements.txt
Add some changes to the doc config, to fix issues with local docs generation. Fixes #841
> Doc config changes

- js/locales/bootstrap-datepicker.tr.js
> Update Turkish locale

- docs/options.rst
add an example on how to use the inputs option
> add example for inputs option

- js/locales/bootstrap-datepicker.nl.js
Names of days and months are lower case in Dutch
> Dutch localisation file update

- js/locales/bootstrap-datepicker.nl-BE.js
See https://onzetaal.nl/taaladvies/advies/oktober-october
> FIX: Days/months should start lowercase

- js/locales/bootstrap-datepicker.fr.js
See https://fr.wikipedia.org/wiki/Usage_des_majuscules_en_fran%C3%A7ais#Jours_de_la_semaine_et_mois_de_l.27ann.C3.A9e
> FIX: Month/daynames should be lowercase

- js/bootstrap-datepicker.js
Moved the clear logic to a seperate function, so that it is also callable directly from the datepicker object
> Added clear method, fixes #857

- README.md
- js/bootstrap-datepicker.js
- `hasClass('<class>')` must work faster (my opinion) than the `is('.<class>')`
- `children('<selector>')` must work faster (my opinion) than `find('> <selector>')`
> Refactoring js/bootstrap-datepicker.js

- js/locales/bootstrap-datepicker.me.js
Added missing Montenegrin translation (bootstrap-datepicker.me.js)
Tests passed.
;-)
> Added Montenegrin locale

- Gruntfile.js
- js/bootstrap-datepicker.js
- package.json
I've added a version property to the datepicker object
TODO:
> Added version to datepicker object

- docs/methods.rst
Took me a while to figure out how to reset/clear the datepicker.
> Add additional documentaion to methods

- index.htm
Added a beforeShowMonth example which was added in #1074. Can be merged after 1.4.0 is released
> Added example for beforeShowMonth callback added in #1074

- index.htm
Added example for dateDisabled option added in #515. Can be merged after 1.4.0 is released
> Added sandbox example for dateDisabled introduced in #515

- index.htm
This pr fixes the missing examples from issues #883 and #893. Merge PR after the 1.4.0 release
> Added some missing examples

- js/bootstrap-datepicker.js
- tests/suites/keyboard_navigation/2012.js
This PR added the down key as a trigger to show the datepicker. Thanks @fabdouglas for the original commits, the PR merges his PR's #1300 & #1301 and re-added the escape key trigger so we don't break BC
Closes: #1302, #827
> Added down key as datepicker show trigger

- js/bootstrap-datepicker.js
Issue #1145 proposed a fix for an issue with prototype, this PR ported the fix
> Ported prototype fix from #1145

- js/bootstrap-datepicker.js
- tests/suites/options.js
Created a PR for a fix in #1137
TODO:
> Fixed issue with startview year

- less/datepicker3.less
http://jsbin.com/sofocuvuge/8/edit
After: #1328.
> Added padding for .datepicker-dropdown.

- build/build3.less
- build/build_standalone3.less
- less/datepicker.less
- less/datepicker3.less
> Fix `grunt dist-css`.

- build/build.less
- less/datepicker.less
- less/datepicker3.less
https://github.com/eternicode/bootstrap-datepicker/pull/1355#issuecomment-89367487
> Support daysOfWeekHighlighted bs-2 too.

- docs/options.rst
- js/bootstrap-datepicker.js
> Added maxViewMode options

- docs/options.rst
> Minor info about TODAY

- js/bootstrap-datepicker.js
- tests/assets/mock.js
- tests/suites/component.js
> Allow overriding `$.fn.show` and `$.fn.hide`

- build/build.less
- build/build3.less
- less/datepicker.less
- less/datepicker3.less
> Adding border-radius variable for LESS

- docs/options.rst
- js/bootstrap-datepicker.js
- tests/suites/options.js
I reproduced `beforeShowDay` behavior.
> Implement `beforeShowYear` as requested in #1226

- js/bootstrap-datepicker.js
Add css-classes for range-start and range-end so they can get styled separately
> Add css-classes for range-start and range-end

- less/datepicker.less
- less/datepicker3.less
> Fix cursor thead styles

- js/bootstrap-datepicker.js
This would fix datepicker crashing on January 0100 dates
> Temporary IE fix

- js/locales/bootstrap-datepicker.hu.js
month and day names are normally lowercase in Hungarian. add month selection header format
> update Hungarian translation

- js/bootstrap-datepicker.js
Fix for https://github.com/eternicode/bootstrap-datepicker/issues/1489
> Issue #1489 wrong month or dates shown

- js/bootstrap-datepicker.js
Fix #1286, #1567, #1529, #1480.
Maybe fix #1517, #1496, #1364, #1146, #1088, #1035.
> Fix vertical orientation

- build/build3.less
- less/datepicker3.less
Update Bootstrap 3 mixin from latest release (v3.3.5)
Before:
1. Open http://eternicode.github.io/bootstrap-datepicker/
2. Select `Type` to `Range`
3. Open datepicker, set range and hover on elements
After:
1. Open: http://jsbin.com/xoyokumido/edit?html,js,output
2. Open datepicker and hover on elements
> Update hover effect for "buttons"

- js/bootstrap-datepicker.js
- tests/suites/methods_jquery.js
- tests/tests.html
> Fix jQuery chain breaks

- js/locales/bootstrap-datepicker.ko.js
In Korea, sunday is the beginning of a new week.
> Changed weekStart to 0

- docs/events.rst
- docs/i18n.rst
- docs/markup.rst
- docs/methods.rst
- docs/options.rst
Change range example BS2 to BS3.
> Some fixes in docs

- docs/options.rst
- js/bootstrap-datepicker.js
- tests/suites/options.js
So, Add the decade picker and century pickers.
This is a rebase of #1437 based on #753.
> PIcking a decade and a century - Rebase of #1437

- Gruntfile.js
- js/bootstrap-datepicker.js
- tests/suites/timezone.js
- tests/timezone.html
Rebase #1524.
Unfortunately for UTC+0 this test is always performed.
> Rebase PR 1524

- docs/options.rst
- js/bootstrap-datepicker.js
- tests/suites/options.js
Rebase of #1624 #1444
Linked issues/PRs : #610 #833 #834 #1007
> Replace arrow entities for glyphicon + template + libs snippets - Rebase of #1624 #1444

- js/locales/bootstrap-datepicker.nb.js
> Added missing date format for norwegian (nb) locale

- js/bootstrap-datepicker.js
> Backported fix for prev arrow on decade and century view. 

- js/bootstrap-datepicker.js
if a specific day of week is disabled, it's header will be given an additional class .disabled.
resolves #1557
> added class .disabled to dow header

- js/locales/bootstrap-datepicker.ca.js
- js/locales/bootstrap-datepicker.de.js
- js/locales/bootstrap-datepicker.it.js
- js/locales/bootstrap-datepicker.pt-BR.js
- js/locales/bootstrap-datepicker.pt.js
> Some extra monthTitle translations

- js/locales/bootstrap-datepicker.ko.js
YYYY-MM-DD is not work properly.
> correct date format

- js/locales/bootstrap-datepicker.en-AU.js
No feature change here, just support for en-AU locale.  All validated locally; let me know if anything is missing.
> Add en-AU (Australian English) locale config

- tests/suites/options.js
> Add tests for PR 1859

- js/locales/bootstrap-datepicker.cs.js
Czech localization was missing `monthsTitle` translation.
> Add missing monthsTitle

- less/datepicker.less
- less/datepicker3.less
After d58e50003727943c514f7a9b5f11ae306b461d24.
> Visibility fix for nav arrows

- bower.json
- composer.json
- package.json
PR to solve the issue of #1921 since Bootstrap 3 is not compatible with jQuery 3 (https://github.com/twbs/bootstrap/issues/16834).
> Do no allow jquery 3

- js/bootstrap-datepicker.js
- tests/suites/options.js
> Fix maxViewMode and navigation switch click

- bower.json
- composer.json
- less/datepicker.less
- less/datepicker3.less
- package.json
> Add support jQuery 3. Bootstrap 2 still available (composer.json)

- js/bootstrap-datepicker.js
In order to improve usage on laptop.
> fix(parseDate) use insensitive regex to support +15d with capslock

- js/locales/bootstrap-datepicker.da.js
I made all the months, days, etc. start with a uppercase character and added the weekStart:1. In Denmark, monday is the first day of week.
> Uppercase + start week at monday (danish standard)

- js/locales/bootstrap-datepicker.oc.js
Occitan : spoken in South France, North Spain and Italy, and Monaco.
> Occitan locale

- js/locales/bootstrap-datepicker.oc.js
just a little change, it's uèi and not ùèi.
> Occitan version update

- js/locales/bootstrap-datepicker.br.js
Add translation file for Breton language (Celtic language spoken in Brittany)
> [l10n]Add breton translation

- js/bootstrap-datepicker.js
Use a notation usable with XHTML
> Make XHTML happy

- js/locales/bootstrap-datepicker.eu.js
Hi,
I've added missing properties in basque language file to display calendar correctly.
Thanks in advance.
| Related tickets | N/A
> Added missing basque language properties

- js/locales/bootstrap-datepicker.sl.js
Week starts on monday in Slovenia
> Added weekStart to slovenian translation

- js/locales/bootstrap-datepicker.ru.js
> add monthsTitle

- js/.jshintrc
- js/locales/bootstrap-datepicker.rs-latin.js
- js/locales/bootstrap-datepicker.rs.js
> Fix Serbian ISO language code

- js/bootstrap-datepicker.js
| Related tickets | fixes #2058
> Fix the visibility of the prev and next arrows for years views

- js/bootstrap-datepicker.js
- tests/suites/options.js
> Added test for PR 2065

- js/bootstrap-datepicker.js
- tests/suites/options.js
| Related tickets | fixes #2113
> Correct prev click on leftArrow template

- js/bootstrap-datepicker.js
| Related tickets | fixes #2093
> Use display:table-cell instead of display:block for today, clear and title

- js/bootstrap-datepicker.js
- tests/suites/options.js
After #2043.
Use data-date attribute always.
> Fix beforeShowDay with content not equal number

- js/locales/bootstrap-datepicker.ta.js
| Related tickets | mentioned in #2119 
> Fix Tamil Language file with proper locale code, see #2119

- js/bootstrap-datepicker.js
| Related tickets | closes #1997
This PR finishes #1997 to fix the tests
> Use default arrow values

- js/bootstrap-datepicker.js
> Fix code-style

- js/locales/bootstrap-datepicker.da.js
| Related tickets | fixes #X, partially #Y, mentioned in #Z
> Added translation for months (fixing the default 'en' locale).

- js/locales/bootstrap-datepicker.cs.js
| Related tickets | fixes #2274 
> Fix cs locale date format

- js/bootstrap-datepicker.js
- tests/suites/options.js
- tests/tests.html
Fixed #2230.
And #2266, #2159,  #2260, #2084?
> Fix navigation buttons states

- js/locales/bootstrap-datepicker.tk.js
This pull request includes a
The following changes were made
- Added bootstrap-datepicker.tk.js file
> Added Turkmen translation file

- dist/js/bootstrap-datepicker.js
This is a bugfix for https://github.com/uxsolutions/bootstrap-datepicker/issues/2385
> startDate and endDate bugfix #2385

- js/bootstrap-datepicker.js
- tests/suites/component.js
| Bug fix?        |yes
| Related tickets | fixes #2451
> Fix for #2451

- js/bootstrap-datepicker.js
- tests/suites/options.js
| Related tickets | fixes #398
> Hide today button when before start or after end date

- js/locales/bootstrap-datepicker.az.js
| Translation?      | yes
| Related tickets | no
> add: missing fields in Azerbaijani locale

- js/locales/bootstrap-datepicker.sq.js
| Related tickets | fixes #X, partially #Y, mentioned in #Z
> Adding properties

- js/bootstrap-datepicker.js
| BC breaks?      | Might need a polyfill
| Related tickets | Fixes #2564 and #2563
> Updated deprecated $.isArray and $.isFunction for jQuery 3

- .github/workflows/ci.yaml
- .travis.yml
> Switch from travis-ci to github actions
