js/bootstrap-datepicker.js
when I use the "today" button with the setting {todayBtn: true}. This should not trigger the event changeDate, because the date in the input field does not change. It changes only with {todayBtn: "linked"}. In _setDate check if (which !== 'view')
=> Using {todayBtn: true} trigger changeDate

js/bootstrap-datepicker.js
Right align calendar instead of aligning left and nudging when the left aligned calendar would cross the right window edge.
This looks prettier because the right calendar edge aligns with the component and the arrow correctly points to the component.
=> Right align calendar on right window edge conflict

js/bootstrap-datepicker.js
On "ENTER" keydown on picker, prevent the closest form to be submitted too.
Updated PR of #674
=> Prevent ENTER propagation on form

js/bootstrap-datepicker.js
Named entities (such as &nbsp;) are not valid in XHTML pages but decimal entities (such as &#160;) are, so this simple enhancement lets the datepicker work in pages served as XHTML.
Without it, upon initialisation, errors are thrown:
- Firefox 29: SyntaxError: An invalid or illegal string was specified
- Chrome 35: Uncaught SyntaxError: Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document
=> Replaced named entities with decimal entities

js/bootstrap-datepicker.js, tests/suites/options.js
An array to specify dates to disable. It also adds the .disabled-date class in order to customise the UI.
Usage:
```javascript
var input = $('<input />').datepicker({
format: 'yyyy-mm-dd',
datesDisabled: ['2012-10-1', '2012-10-10', '2012-10-20']
}),
```
=> datesDisable option

docs/options.rst, js/bootstrap-datepicker.js, tests/suites/options.js
When the calendar is initially opened, go to a day other than "today".
=> Option default view date

docs/options.rst, js/bootstrap-datepicker.js, tests/suites/options.js
This option prevents the date from becoming unset when clicking on the currently active date.
The current default is set to match the previous behavior.
The option is ignored when multidate is active (as there would be no easy way to unselect a date, once selected).
=> Add toggleActive option

js/bootstrap-datepicker.js
This PR backports some placement fixes from #822 for new the new container option added in #918. With these fixes the datepicker should always be positioned correctly even when appended to a element with a fixed position
Fixes: #384, #410, #325
Thanks  @pkracht for the original code!
=> Backported some placement fixes for the container option

js/bootstrap-datepicker.js
Assigning the plugin to a local variable so that we can call it without invoking it as a jQuery plugin.  Before this, noConflict was not really noConflict as there was still a reliance on .datepicker()
=> Fix for #1112, assigning plugin to a local variable

docs/options.rst, js/bootstrap-datepicker.js, tests/suites/options.js
This option fixes #1231. The default behavior is restored and displaying of the datepicker can be disabled for readonly inputs if a users wants it that way.
Not sure if the option name is a good name
=> Added option to not show datepicker on readonly field

docs/options.rst, js/bootstrap-datepicker.js
"As of jQuery 1.7, the .on() method is the preferred method for attaching event handlers to a document." (http://api.jquery.com/bind/)
=> Use $.on() instead $.bind().

js/bootstrap-datepicker.js, tests/suites/events.js
Addresses #778 
Note: the test I added currently fails. The reason is that the expected UTC date is off:
>> Events - paste must update the date
>> Message: null
>> Actual: "2015-07-22 00:00:00.00"
>> Expected: "2015-08-22 00:00:00.00"
>> at datesEqual (file:///Users/rhogg/src/datePicker/tests/assets/utils.js:20)
Two existing tests fail on master (without any of my changes) for the same reason, so I'm not sure what to do. Either I could a) doctor the test so it passes and add a FIXME or b) leave it as is or c) fix the test because I'm doing something wrong, it's up to you.
=> Enables right-click and edit-menu paste for the datepicker

docs/options.rst, js/bootstrap-datepicker.js, tests/suites/options.js
Fixes #1323.
> immediateUpdates
> ---------------------
> 
> Boolean. Default: false
> 
> If true, selecting a year or month in the datepicker will update the input value immediately. Otherwise, only selecting a day of the month will update the input value immediately.
=> Add immediateUpdates option (updates input when a year or month is selected)

js/locales/bootstrap-datepicker.pl.js
I would like to propose better from Polish grammatical point of view language translation for weekdays, months and their shortcuts.
Added default date format.
=> Better Polish language date shortcuts translation and default date format

docs/options.rst, js/bootstrap-datepicker.js, less/datepicker3.less, tests/suites/options.js
I was looking for a feature that can do a bit more than daysOfWeekDisabled : Highlight some day(s) highlighting without disabling them. 
This is usefull for highlighting weekend for example.
The code is almost the same as the daysOfWeekDisabled feature, without the disabling part.
=> Feature : Days of week highlighted

js/bootstrap-datepicker.js, tests/suites/events.js
This PR fixes the issue with a date change firing multiple change events as reported in #1233 
Fix is pulled from [this issue](https://github.com/vizjerai/bootstrap-datepicker/issues/4) and [this commit](https://github.com/vizjerai/bootstrap-datepicker/commit/db20cae1d6ada09c9693fb780567388508b3ff57)
I've tested this locally and all seems to be working OK with it.
=> Fixes the issue with a date change firing mulitple change events

bower.json
The official bootstrap package can be avoided for those who are using the official bootstrap-sass source. No need to download the LESS version.
=> Update bower.json dependencies

package.json
This will enable the datepicker to be included via `require('bootstrap-datepicker')` when using browserify/webpack.
=> Include "main" property in package.json

.gitignore
Adding .gitignore to gh-pages branch will make switching back and forth between branches less annoying.
I've just added node_modules to the list for now.
=> Add .gitignore to gh-pages branch to ease branch switching

js/bootstrap-datepicker.js
Hello!
This PR is fix for #1227, now we cache fatty jQuery object, and this works from 20% to 90% faster.
(20 for [selection by id](http://jsperf.com/caching-jquery-objects-perf/18)) (90 for [selection by class](http://jsperf.com/caching-jquery-objects-perf/13))
=> Small performance fix

composer.json, docs/index.rst, package.json
Also updates the homepage URL for Bootstrap.
Since version 3, Bootstrap is no longer organizationally affiliated with Twitter.
See http://getbootstrap.com/about/#name and https://github.com/twbs/bootstrap/issues/9899
=> "Twitter Bootstrap" => "Bootstrap"

bower.json
The bower package is pointing at the pre-build bootstrap-datepicker.js.  This changes it to point at the dist version.
=> point the bower package at the dist/*.js rather than js/*.js

js/bootstrap-datepicker.js
When in a custom setup (I have two inline pickers in a bootstrap collapse div), the  click event from the collapse trigger will set `style="display:none"` on the two inline pickers. Testing for the `.datepicker-inline` class on the picker will inhibit this (unwanted) behaviour.
=> Do not hide inline picker

README.md
@acrobat I think that the readme should lead people to the last stable docs instead to the dev docs. 
It might help avoid misunderstanding like in #1407.
=> Link to last stable release docs instead of dev docs

docs/options.rst
To avoid future confusion of forgetting to place a 'd' after the 0.
=> added example to end-date

bower.json
Bootstrap has done it. We as well. Update the bower.json file to only include one line per file type.
Only the main CSS file is listed then.
Ref: https://github.com/bower/bower.json-spec/pull/43
=> Update json accordingly the latest definition

docs/methods.rst
I was looking for a method to update the datesDisabled value.
Until I discovered that it had already implemented but not documented yet.
=> added setDatesDisabled method to documentation

js/bootstrap-datepicker.js
previously clicking on an element outside of the datepicker didn't go through the usual hide method, thus forceParse was ignored, leaving invalid dates in the input field
=> fix hiding

js/bootstrap-datepicker.js
If you want to init a datepicker (range or not) after remove a range one on the same input(s), an error was throw.
The case is if you want to dynamically change a range picker to a solo picker.
To test with the [online demo](http://eternicode.github.io/bootstrap-datepicker), choice range then run that in the console:
```js
$('#datepicker').datepicker('remove');
$('#datepicker input[name=start]').datepicker({});
```
I try many cases with remove (included call remove on each range children).
[EDIT] Forgot to say, the error is throw only if a value as been add to the input before removing range.
=> Fix bug on Range

docs/options.rst, js/bootstrap-datepicker.js, tests/suites/options.js
Previously, the height was computed to be 10 higher than the max height of all of the input's parents. In some cases where the datepicker needs to move/scroll around with the page, it may collide with other fixed elements. In those cases, a configurable z-index is very helpful in order to keep the datepicker visible.
Please let me know if I should also be regenerating the `dist` assets as well. I couldn't infer from the contribution guidelines. Thank you!
=> Add the zIndexOffset option to configure the dialog "height"

CHANGELOG.md
The updates are taken directly from the release description at:
https://github.com/eternicode/bootstrap-datepicker/releases/tag/v1.4.0
=> Update CHANGELOG for 1.4.0

js/bootstrap-datepicker.js, tests/suites/options.js
Sometimes our customers copy and paste dates from documents in the date fields, and hit enter after that. The regular forceParse setting does change that in a (sometimes completely wrong) valid  date, which then passes validation unnoticed. 
Setting forceParse to false should stop this behaviour, but it doesn't. (It works correctly on focus out, but not on enter), so we had to patch:
$('[id$="_date_string"]').on('keydown', function(e){
if (e.keyCode == 13){
stopImmediatePropagation(e);
return false;
}}).datepicker({endDate: '+0d', forceParse: false});
It would be very nice if this behaviour was already in the library, as it is quite confusing to set forceParse to false and still have forced parsing on false...
=> forceParse = false doesn't apply on enter

js/bootstrap-datepicker.js, tests/suites/methods.js
When typing/pasting an invalid formatted date into the textbox (e.g. 2000-1-1 for a picker with mm/dd/yyyy) into a box, the browser will stall when clicking next.
I've traced the issue to the date-resetting loop in the moveMonth.
=> Fix date-reset issue when navigating to next with invalid date

js/bootstrap-datepicker.js
When closing the picker because ESC was pressed, stop propagating the keydown event, because the datepicker has already 'consumed' the key event. If the event is allowed to bubble up enclosing modal windows or dialogs might be closed as well.
=> Swallow ESC-key on hide

build/build3.less, build/build_standalone3.less, less/datepicker.less, less/datepicker3.less
Add the Bootstrap variables for the arrow of the datepicker:
=> Add support for dropdown border variables

docs/options.rst
Fixed error in document. Month begins from 0, which was quite confusing.
=> Correct default month value of defaultViewDate in Doc.

js/bootstrap-datepicker.js
`hide` event is being triggered correctly when popup is dismissed with escape key, by tabbing to next field or clicking date or clear button. This change makes it trigger also popup is dismissed by clicking outside.
=> Trigger "hide" event on click outside

docs/options.rst, js/bootstrap-datepicker.js, tests/suites/formats.js
Rebase / modification of #1556. My hope is that this can be merged.
If the user opts-in by setting `options.assumeNearbyYear` = true:
- When a user enters a 2 digit year, the code now does a better job of
guessing intent. If the 2 digit year is more than 10 years in the future,
it'll use the past century instead. So in the 2015, a value between 00-25
would assume the century is 2000. For 26-99, it'll assume the user meant
1900 (e.g. 1/31/10 = Jan 31, 2010, 1/31/26 = Jan 31, 1926). People don't
generally enter future dates too far in advance, but it's very common
to enter dates from 50+ years ago.
=> Add "assumeNearbyYear" option

js/bootstrap-datepicker.js, tests/suites/methods.js
Rejecting Unicode characters in `nonpunctuation` is added in #294 to support yyyy年mm月dd format. However rejecting all Unicode in the range \u3400 to \u9fff rejects names of Chinese months too. And calling parseDate with Chinese date having the month format as  MM results in today's date always irrespective of the date passed. Hence don't reject all the Unicode and reject only the three Unicode in Japanese date format.
=> Changes nonpunctuation to accept unicode characters

docs/index.rst, docs/options.rst, js/bootstrap-datepicker.js, tests/suites/options.js
1. Highlighted `templates` options and indent unification (4 whitespace).
2. Fix screenshot and default arrows for Bootstrap 2 (still support).
For reproduce open `/docs/_screenshots/demo_head.html` and write `setup()` in console.
=> Fix default arrows for BS2 and screenshots (for docs)

docs/options.rst, js/bootstrap-datepicker.js, tests/suites/options.js
The event `beforeShowMonth` could only disable the cells.
I extended it with the functionality of `beforeShowDay` so you can disable, add classes and set a tooltip.
Backwards compatibility is given.
Tests are added and documentation is extended.
=> Extend beforeShowMonth event functionality to work like beforeShowDay and beforeShowYear

tests/suites/events.js
preventDefault function expected by jQuery 2.2.1
not sure if:
ok(evt.originalEvent.isDefaultPrevented, 'prevented original event');
should be added to test.
=> originalEvent object needs preventDefault fn

js/bootstrap-datepicker.js, tests/suites/options.js
Adds an option to add a data-date attribute with a timestamp representative of that cell's date. This makes bootstrap-datepicker more extensible when using callbacks.
Have not run
`grunt dist`
Added unit tests as well.
=> Adding dateCells option

js/bootstrap-datepicker.js
With the templating system, we are now able to define the left and right arrows.  Users may end up using font icons that typically follow the common empty span with icon class name: `<span class="icon-right-arrow"></span>`.
While the font icons show as expected, they are being prematurely selected by jQuery since the code assumes only span elements will only exist for the month listing and not the next/prev arrows which by default are characters.  You can replicate this by selecting a date in the below jsfiddle, and then clicking on the month name to enter the month listing.  You will see that the active class incorrectly applies itself two months before the actual active month.  A similar (same?) issue appeared on the original bootstrap-datepicker …
=> Fix jQuery selector from premature selection of span element in inline/embedded calendar's month selection

js/bootstrap-datepicker.js, tests/suites/methods.js
Instead of directly comparing date values using valueOf, dates are now compared with arithmetic to check if they fall under the same date. This fixes resolves #1221, allowing for times other than 00:00:00 when setting the date.
=> Use date arithmetic to allow dates with times other than 00:00:00

docs/options.rst, js/bootstrap-datepicker.js, tests/suites/options.js
If this option is set to true, it will stop propagation of a selected
date to other, currently empty, pickers in a date range setup.
Default for this option is false, to keep the current behavior.
fixes #1454
=> added keepEmptyValues option

docs/options.rst, js/bootstrap-datepicker.js, tests/suites/options.js
Hi.
I moved keepEmptyValues documentation to correct alphabetical position,
added keepEmptyValues to quick reference table,
added keepEmptyValues to defaults array and
fixed tests
as suggested by comments of @acrobat in #1558
=> keepEmptyValues followup

js/bootstrap-datepicker.js, tests/suites/events.js
Fixes #1561
Fixes #1512
Fixes #1846
... and probably more, please add them if you can.
Also includes relevant test.
=> Do not trigger change or changeDate on initialization

js/bootstrap-datepicker.js, tests/suites/touch_navigation/all.js, tests/tests.html
It seems that when the event system was reworked, the bug closed in https://github.com/eternicode/bootstrap-datepicker/pull/223 got reintroduced. This PR fixes this.
=> Fix: Close datepicker on touchstart

js/bootstrap-datepicker.js, tests/suites/options.js
Setting multiple datesDisabled through a data attribute is currently broken, because the _process_options function assumes that if that value is not already an array it is only one datestring. This is not always the case; if you try to pass multiple dates to the data-date-dates-disabled attribute they will be interpreted as one long string and fail to parse as dates. Fixed by calling `.split(',')` on the raw value. Strings without commas will simply be wrapped in an array, which is the current behavior.
=> Fix data-date-dates-disabled attribute to accept a comma-separated list

js/bootstrap-datepicker.js, tests/suites/events.js
Adds a "changeViewMode" event (triggered by navArrowsClick). Also adds the current `viewMode` to any triggered events.
So now you can watch `changeViewMode` and depending on the `event.viewMode` and the `event.date` you can do something..
The reasoning was that on a `viewMode` change I wanted to be able to get dates by viewMode range from a backend and then redraw the component ...
=> added "changeViewMode" event; also adds the current `viewMode` to events

js/bootstrap-datepicker.js, tests/suites/formats.js
Remove copypasta (eddd51d25247cb8a1dc8bee1302850e2bff13753) and add tests.
First, let's merge #1910. Then I'm doing here rebase.
=> Refactoring timedelta aliases (dateAliases)

js/bootstrap-datepicker.js
Need for correct recreate DateRangePicker on same inputs.
=> Remove listen `changeDate` after destroy DateRangePicker

tests/suites/methods.js
Tried to reproduce #1980 in tests but wasn't able. But tests ware always good. :-)
=> add tests for setDatesDisabled function

docs/options.rst
[Doc] Keyboard navigation is not supported for embedded / inline type at all.
Fixes #1263
=> [Doc] Keyboard navigation is not supported for embedded / inline type

js/bootstrap-datepicker.js
On days when DST is added this results in getDate call returning the incorrect day. 
As an example on October 2, 2016 many parts of Australia move from AEST to AEDT.  Clicking on October 2, 2016 and then triggering datepicker('getDate') results in October 1, 2016 being returned.
Here is a JSFiddle demonstrating the issue (with instructions): https://jsfiddle.net/kylethielk/x6eafu3g/
Here is a JSFiddle with my proposed changes that resolve the issue:
https://jsfiddle.net/kylethielk/aea7jobw/2/
Let me know if you have any questions.
=> resolves bug on days when DST is added.

docs/options.rst, js/bootstrap-datepicker.js, tests/suites/options.js
Implementation details are present in updated docs and added test. Default value does not change any existing behaviour.
I think this option will be helpful if you interact with bootstrap-datepicker via code. It allows you a more granular control how bootstrap-datepicker reacts on changes. It will be really powerful together with `setViewDate` method suggested in #1978.
Please have a review on syntax used in docs. I'm not quite sure if lists are supported and wasn't able to build docs to verify.
=> adds `updateViewDate` option

docs/options.rst
| Related tickets | fixes #2051
Fix documentation to be more clear about month parameter being zero based on the defaultViewDate option
=> Improve defaultViewDate documentation

docs/methods.rst
| Related tickets | fixes #2038
=> Add notes about multiple dates and examples for update method

CHANGELOG.md, docs/options.rst, js/bootstrap-datepicker.js, tests/suites/options.js
| New feature?    | yes
| Related tickets | fixes #1611 (at least for the OP's use case where all three values are set) and #1550
=> Allow Date/String for defaultViewDate option

.travis.yml, js/.jshintrc, js/bootstrap-datepicker.js, package.json
1. Fix deprecation warning without use alias function.
1. Use Latest Node.js LTS on travis.
1. Fix jshint error.
1. Remove unnecessary dupe start `_process_options` functions.
=> Fix deprecation message and jshint fixes

package.json
Tests were hanging at 
> Running "qunit:main" (qunit) task
> Testing tests/tests.html 
and never finish. Updating dependencies fixed it for me.
My configuration:
```
$ nodejs -v
v6.9.4
$ npm -v
3.10.10
$ grunt --version
grunt-cli v1.2.0
grunt v0.4.5
```
| Related tickets | 
=> update grunt and other dev-dependencies

.gitignore, js/locales/bootstrap-datepicker.ta-IN.js
| New feature?    | yes, Indian Tamil Language Translation
| Related tickets | no
| License         | Apache License v2.0
**Demo:**
https://b2oplus.github.io/bootstrap-datepicker/
=> Tamil Language support

js/bootstrap-datepicker.js
=> Refactor _setDate params in dayCellClick

docs/options.rst
The assumeNearbyYear option was between options starting with an 'f'. Moved it to the correct alphabetical order.
| Related tickets | fixes #X, partially #Y, mentioned in #Z
=> moved assumeNearbyYear to correct location

README.md
=> Add npm on README.md

js/locales/bootstrap-datepicker.ro.js
| Related tickets | 
Corrected the date format for Romanian locale.
=> Romanian uses dd/mm/yyyy format for dates

package.json
| New feature?    | yes
| BC breaks?      | should not
After this patch `jquery` is removed from the `dependencies` section of `package.json` and granted `peerDependencies` status instead of it.
Rationale:
- Both of these packages (`bootstrap-datepicker` and `jquery`) are quite likely to be defined as dependencies of their common parent application (which is, most likely, a web site; could also be an application built on [Electron](http://electron.atom.io/), [NW.js](http://nwjs.io/), [JXcore for Cordova](https://github.com/jxcore/jxcore-cordova/), etc.) and thus to become peers in that sense. Currently, if some version mismatch happens on that level (under that common parent), `npm` would install …
=> move `jquery` to `peerDependencies` from `dependencies`

package.json
Reverts uxsolutions/bootstrap-datepicker#2163
Fixes #2206 
If necessary we can introduce this change in 2.0
=> Revert "move `jquery` to `peerDependencies` from `dependencies`"

js/locales/bootstrap-datepicker.lv.js
Hi,
I've added missing "monthsTitle" property in Latvian language.
Thanks.
| Related tickets | N/A
=> Added monthsTitle to Latvian locale

less/datepicker3.less
Removed text-shadow from input-group-addon to match bootstrap3 input-group-addon
| Related tickets | fixes #2340 
=> Removed text-shadow from input-group-addon

js/locales/bootstrap-datepicker.sv.js
Days and months are lowercase in Swedish
| Related tickets | fixes #X, partially #Y, mentioned in #Z
=> Change Swedish days and months to lowercase

js/bootstrap-datepicker.js
| Bug fix?        |Yes
| New feature?    | No
| BC breaks?      | No
| Related tickets | N/A
The library `bootstrap-datepicker` uses its constructor's prototype to store the events attached to any newly initialized DatePicker component. It never cleans up the `_events` property, thus causing memory leaks even after you call `.datepicker('remove')`.
After testing my App for memory leaks, I found references to `DatePicker` when running heap snapshots, so I decided to check what was going on: tried to open the search view, open the inbox view, back to the search view, then to a lead page, back to the search view etc, and you can see that the `_events` keep growing:
Checked my code, and `.datepicker('remove')` is correctly …
=> Move _events to the instance avoiding memory leaks

js/locales/bootstrap-datepicker.no.js
=> rename "vovember" to correct "november"

js/locales/bootstrap-datepicker.en-US.js
| BC breaks?      | don't understand that.
| Related tickets |  no
differences to en-GB:
- `weekStart: 0` instead of `weekStart: 1`
- `format: dd/mm/yyyy` instead of `format: m/d/yyyy`
disclaimer: I'm not native us american - changes based on internet research.
=> introduce en-US locale

package.json
| Related tickets | none
It fixes: https://nvd.nist.gov/vuln/detail/CVE-2019-11358
=> [CVE-2019-11358] Fix vuln jquery <3.4.0

docs/options.rst
todayHighlight is actually `false` by default; the defaults table incorrectly showed it as being `true` in conflict with the documentation higher up on the page.
| Related tickets | 
=> todayHighlight defaults table entry wrong

docs/options.rst, tests/suites/component.js, tests/suites/options.js
There is a small typo in docs/options.rst.
Should read `millennium` rather than `millenium`.
=> docs: Fix simple typo, millenium -> millennium
